language: c
script: bash -ex .travis-ci.sh
sudo: required
env:
  global:
  - PINS="mirage mirage-types mirage-types-lwt dns:git://github.com/yomimono/ocaml-dns.git#standardize_record_fields"
  matrix:
  - OCAML_VERSION=4.02 PACKAGE=tcpip MIRAGE_MODE=unix
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.02 PACKAGE=tcpip MIRAGE_MODE=xen
