language: c
script: bash -ex .travis-ci.sh
sudo: required
env:
  global:
  - EXTRA_REMOTES="https://github.com/yomimono/mirage-dev.git#split-tcpip-module-types-consistent"
  matrix:
  - OCAML_VERSION=4.03 PACKAGE=tcpip MIRAGE_MODE=unix
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.03 PACKAGE=tcpip MIRAGE_MODE=xen
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.04 PACKAGE=tcpip MIRAGE_MODE=ukvm
  - OCAML_VERSION=4.04 PACKAGE=tcpip MIRAGE_MODE=unix
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.04 PACKAGE=tcpip MIRAGE_MODE=xen
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.04 PACKAGE=tcpip MIRAGE_MODE=ukvm
