language: c
script: bash -ex .travis-ci.sh
sudo: required
env:
  matrix:
  - OCAML_VERSION=4.04 PACKAGE=tcpip MIRAGE_MODE=unix
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.04 PACKAGE=tcpip MIRAGE_MODE=xen
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.05 PACKAGE=tcpip MIRAGE_MODE=ukvm
  - OCAML_VERSION=4.06 PACKAGE=tcpip MIRAGE_MODE=unix
